# .github/workflows/firebase-hosting-main.yml

name: Deploy a Firebase Hosting (Rama Main)

# Define cuándo se ejecutará este workflow
on:
  push:
    branches:
      - main # <--- Solo se ejecuta en pushes a la rama 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Usamos un entorno Linux

    steps:
      # 1. Checkout: Clona el código del repositorio
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Configurar Node.js (asegúrate de la versión que usas localmente)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajusta esto a tu versión de Node (ej: 18, 20)

      # 3. Cachear dependencias (para acelerar futuras ejecuciones)
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Instalar dependencias
      - name: Install Dependencies
        run: npm install

      # 5. Construir la aplicación Vue (genera la carpeta 'dist')
      - name: Build Vue App
        run: npm run build
        env:
          # Si tienes variables de entorno en Vue, configúralas aquí
          NODE_ENV: production

      # 6. Desplegar a Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # Token generado por GitHub para la acción
          firebaseServiceAccount: '${{ secrets.FIREBASE_DEPLOY_TOKEN }}' # <--- ¡Aquí usamos tu Token Secreto!
          channelId: live # Despliega a la URL principal (el canal 'live')
          projectId: prueba1-esmn